apiVersion: v1
kind: LimitRange
metadata:
  name: socket-autofill
  namespace: socket-autofill
  labels:
    app.kubernetes.io/instance: socket-autofill
spec:
  limits:
    - default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 50m
        memory: 50Mi
      type: Container
