apiVersion: v1
kind: ResourceQuota
metadata:
  name: socket-autofill
  namespace: socket-autofill
  labels:
    app.kubernetes.io/instance: socket-autofill
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "250Mi"
    limits.cpu: "200m"
    limits.memory: "500Mi"
    services.nodeports: "0"
    services.loadbalancers: "0"
    requests.ephemeral-storage: "0"
    limits.ephemeral-storage: "0"
    local-path.storageclass.storage.k8s.io/requests.storage: "0"
    longhorn.storageclass.storage.k8s.io/requests.storage: "0"
    longhorn-static.storageclass.storage.k8s.io/requests.storage: "0"