apiVersion: v1
kind: Secret
metadata:
  name: env
  namespace: socket-autofill
  labels:
    app.kubernetes.io/instance: socket-autofill
stringData:
  MONGODB: "<path:secret/data/apps/socket-autofill#mongodb>"
